chat function
FriendsWithTools/FriendsWithTools pull request #51
Opened 2024-07-09 10:23 UTC by jemimacecil

2024-07-09 10:57 UTC, Wyna-7 requested changes
Looks amazing!
Before merging, could you remove the logs/comments we don't need, and resolve the conflicts?

2024-07-09 10:57 UTC, Wyna-7 commented on app/api/webhooks/user/route.ts
> +  console.log('body', body)
we can remove this log

2024-07-09 10:57 UTC, Wyna-7 commented on app/components/RequestToolCard.tsx
> +  console.log("hello")
can we remove this log?

2024-07-09 10:57 UTC, Wyna-7 commented on server.ts
>  // import { createServer } from 'http';
can we remove the commented out imports?

2024-07-10 08:48 UTC, Wyna-7 approved these changes

2024-07-10 09:00 UTC, Elsass1 approved these changes

2024-07-10 09:00 UTC, merged